# Generated by Django 3.2.25 on 2024-07-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='suther',
            new_name='author',
        ),
    ]
